### ISSUE TITLE
dap-go.lua:139: attempt to index lo cal 'result' (a nil value)

### ISSUE THREAD

**Issue by waldirborbajr** [leoluz/nvim-dap-go#9] opened 2022-06-04 00:50 UTC
Error: on execute debugging on GOLang 1.18.3

NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

E5108: Error executing lua ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:139: attempt to index lo
cal 'result' (a nil value)
stack traceback:
        ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:139: in function 'get_closest_test'
        ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:226: in function 'debug_test'
        [string ":lua"]:1: in main chunk

**Comment by ismet55555** [comment] 2022-06-25 01:08
Exact same issue. Go 1.18, nvim v0.7.0, LuaJIT 2.1.0-beta3

**Comment by cabemo** [comment] 2022-07-20 22:52
I'm having the same issue. In my case the `tests_query` (and `subtests_query` maybe) is not matching the test I'm trying to debug. 
When trying to debug a file that looks like:
```go
package util

import (
	"testing"
)

func TestSomeFunc(t *testing.T) {
	t.Errorf("Some %d error", 0)
}
```
It works perfectly. But when using another test package or some weird test notation other than the tree-sitter queries support it throws that error.
These are the queries used:
```lua
local tests_query = [[
(function_declaration
  name: (identifier) @testname
  parameters: (parameter_list
    . (parameter_declaration
      type: (pointer_type) @type) .)
  (#match? @type "*testing.(T|M)")
  (#match? @testname "^Test.+$")) @parent
]]

local subtests_query = [[
(call_expression
  function: (selector_expression
    operand: (identifier)
    field: (field_identifier) @run)
  arguments: (argument_list
    (interpreted_string_literal) @testname
    (func_literal))
  (#eq? @run "Run")) @parent
]]

```
*Side note: You can't debug soft links to files*

So maybe the queries should be more general to support various testing packages and naming conventions? (e.g. check.v1)

**Comment by ronthl** [comment] 2022-09-01 05:19
I got the same issue on:
* MacOS Monterey v12.5.1.
* go1.19 darwin/arm64
* nvim v0.7.2
* LuaJIT 2.1.0-beta3

**Comment by leoluz** [comment] 2022-11-01 02:09
> I'm having the same issue. In my case the `tests_query` (and `subtests_query` maybe) are not matching the test I'm trying to debug. 


@cabemo Thank you for the great analysis! It will help fixing the issue. I just need to find time to work on it. Let me know if you want to give it a try.

**Comment by leoluz** [comment] 2022-11-01 02:46
Can someone please add an example of a test code that doesn't work with this plugin? I need something to reproduce because all tests I debug are working with no issues.

**Comment by tasdikrahman** [comment] 2023-04-25 09:47
Hello there, thanks for your time, to just add to the last comment, a sample snippet for https://github.com/onsi/ginkgo

```
package utils

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("foo", func() {
	Context("a test case", func() {
		It("will return true", func() {
			// test setup

			Expect(ourAssertion.Method(foo)).To(Equal(true))
		})
	})
})
```

Gives the same error as 
```
E5108: Error executing lua /Users/UserName/.vim/bundle/nvim-dap-go/lua/dap-go.lua:175: attempt to index local 'result' (a nil value)
stack traceback:
        /Users/UserName/.vim/bundle/nvim-dap-go/lua/dap-go.lua:175: in function 'get_closest_test'
        /Users/UserName/.vim/bundle/nvim-dap-go/lua/dap-go.lua:262: in function 'debug_test'
        [string ":lua"]:1: in main chunk
```

**Comment by leoluz** [comment] 2023-05-19 18:43
@tasdikrahman Thank you! This plugin doesn't have support for Ginkgo and I have no intention to implement it as I don't use it. It seems that you need the ginkgo binary to be able to run your specs. What you can do is wrap the spec you want to debug in a standard go test and debug that test.

I am closing this for now.

**Closed by leoluz** 2023-05-19 18:43 UTC
